apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-nginx-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: my-nginx-pv